version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest 


  api:
    image: ${DOCKER_REGISTRY:-quickstart}/api
    build:
      context: .
      dockerfile: src/Api/Dockerfile


  identityserveraspnetidentity:
    image: ${DOCKER_REGISTRY:-quickstart}/identityserveraspnetidentity
    build:
      context: .
      dockerfile: src/IdentityServerAspNetIdentity/Dockerfile


  javascriptclient:
    image: ${DOCKER_REGISTRY:-quickstart}/javascriptclient
    build:
      context: .
      dockerfile: src/JavaScriptClient/Dockerfile


  mvcclient:
    image: ${DOCKER_REGISTRY:-quickstart}/mvcclient
    build:
      context: .
      dockerfile: src/MVCClient/Dockerfile

